-- Generation logic for the `xmake readme` task (see xmake.lua).
--
-- Pure Lua: given the header list (each entry {name = "bas_x.h", content =
-- "<file text>"}) and the current README text, `render` returns the README with
-- the library table between the markers regenerated. All file access and the
-- xmake task wiring live in xmake.lua.

local START_MARK = "<!-- LIBRARY TABLE START -->"
local END_MARK = "<!-- LIBRARY TABLE END -->"

local function pad_right(s, w)
    return s .. string.rep(" ", w - #s)
end

local function center(s, w)
    local total = w - #s
    local left = math.floor(total / 2)
    return string.rep(" ", left) .. s .. string.rep(" ", total - left)
end

function render(headers, readme)
    -- Scrape each header's title line into {name, version, desc} rows.
    local rows = {}
    for _, header in ipairs(headers) do
        local first = (header.content or ""):match("[^\r\n]+") or ""
        local version, desc = first:match("^/%*%s*bas_%S+%.h%s*%-%s*v([%d%.]+)%s*%-%s*(.-)%s*%-%s*%(bas%)")
        if version then
            desc = desc:sub(1, 1):upper() .. desc:sub(2)
            table.insert(rows, {name = header.name, version = version, desc = desc})
        else
            print("readme: skipping " .. header.name .. " (unrecognized title line)")
        end
    end
    assert(#rows > 0, "readme: no bas_*.h headers with a recognizable title line")
    table.sort(rows, function(a, b) return a.name < b.name end)

    -- Column widths, including the header labels.
    local h1, h2, h3 = "Library", "Version", "Description"
    local w1, w2, w3 = #h1, #h2, #h3
    for _, r in ipairs(rows) do
        r.link = string.format("[%s](%s)", r.name, r.name)
        w1 = math.max(w1, #r.link)
        w2 = math.max(w2, #r.version)
        w3 = math.max(w3, #r.desc)
    end

    -- Assemble the markdown table.
    local lines = {}
    table.insert(lines, string.format("| %s | %s | %s |", pad_right(h1, w1), center(h2, w2), pad_right(h3, w3)))
    table.insert(lines, string.format("| %s | %s | %s |", string.rep("-", w1), ":" .. string.rep("-", w2 - 2) .. ":", string.rep("-", w3)))
    for _, r in ipairs(rows) do
        table.insert(lines, string.format("| %s | %s | %s |", pad_right(r.link, w1), center(r.version, w2), pad_right(r.desc, w3)))
    end

    local block = START_MARK .. "\n"
        .. "<!-- Generated by `xmake readme` from each header's title line. Do not edit by hand. -->\n"
        .. table.concat(lines, "\n") .. "\n" .. END_MARK

    -- Splice the block between the markers.
    local s = readme:find(START_MARK, 1, true)
    local e = readme:find(END_MARK, 1, true)
    assert(s and e, "readme: table markers not found in README.md")
    return readme:sub(1, s - 1) .. block .. readme:sub(e + #END_MARK)
end
